CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  "openId" TEXT UNIQUE,
  name TEXT,
  username TEXT,
  avatar TEXT,
  email TEXT,
  "loginMethod" TEXT,
  role TEXT DEFAULT 'user',
  "subscriptionTier" TEXT,
  "stripeCustomerId" TEXT,
  "stripeSubscriptionId" TEXT,
  "subscriptionStatus" TEXT,
  "subscriptionEndsAt" TIMESTAMP,
  "onboardingCompleted" BOOLEAN DEFAULT false,
  "readingGoalPagesPerWeek" INTEGER,
  "favoriteGenres" TEXT,
  "notificationsEnabled" BOOLEAN DEFAULT true,
  "emailVerified" BOOLEAN DEFAULT false,
  "emailVerificationToken" TEXT,
  "emailVerificationExpires" TIMESTAMP,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "lastSignedIn" TIMESTAMP
);
